services:
  - type: web
    name: cafe701-monitor
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config python:gunicorn_config --worker-class gthread --workers 1 --threads 20 --bind 0.0.0.0:$PORT server:app
    envVars:
      - key: OCR_API_KEY
        value: helloworld
      - key: POLL_INTERVAL
        value: "8"
      - key: PYTHONUNBUFFERED
        value: "1"
